version: '3'
services:
  nginx_master:
    build: https://github.com/nginxinc/docker-nginx.git#:stable/alpine
    volumes:
      - ./conf.d/master:/etc/nginx/conf.d
      - ./log:/var/log/nginx/
    ports:
      - "8888:80"
    depends_on:
      - node_env      
  node_env:
    # image: node:10.16.3-alpine
    build: .
    volumes:
      - ../../code:/home/node/code
    #   - ./sites-enabled:/etc/apache2/sites-enabled
      #- ./hosts:/etc/hosts
    expose:
      - "3000"
    ports:
      # - "3010-3020:3000"  # using for scale (replicate)
      - "3010:3000"
    tty: true
    depends_on:
      - mongo_env
    # networks: 
    #   static-network: 
    #     ipv4_address: 172.20.128.2 
  mongo_env:
    image: mongo:4.0.12-xenial
    volumes:
      - ../../db:/data/db
    #   - ./git_server/log:/var/log/nginx
    #   # - ./git_server/ssh_key:/root/.ssh
    #   - ./git_server/html:/var/www/html
    ports:
      - "27017:27017"
# networks: 
#   static-network: 
#     ipam: 
#       config: 
#         - subnet: 172.20.0.0/16 
#           ip_range: 172.28.5.0/24     
